[package]
name = "ressapanda"
version = "0.2.0"
edition = "2024"
description = "A 3D voxel editor built in Rust with wgpu and egui"
license = "GPL-3.0-or-later"
repository = "https://github.com/TimotyEnder/Ressapanda"
readme = "README.md"
keywords = ["voxel", "3d", "graphics", "editor", "modeling"]
categories = ["graphics", "game-development"]

[dependencies]
anyhow = "1.0.104"
bytemuck = "1.25.2"
cgmath = "0.18.0"
egui = "0.36.2"
egui-wgpu = "0.36.2"
egui-winit = "0.36.2"
env_logger = "0.11.11"
image = { version = "0.25.10", default-features = false, features = ["png"] }
log = "0.4.34"
pollster = "1.0.1"
wgpu = "30.0.1"
winit = "0.30.13"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
egui-file-dialog = "0.15"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true
